FROM nginx:alpine

# Creamos la ruta exacta dentro del contenedor de Nginx
RUN mkdir -p /usr/share/nginx/html/client/assets

# Copiamos TODO el contenido de tu carpeta actual ahí dentro
COPY . /usr/share/nginx/html/client/assets/